# Generated by Django 4.1 on 2022-10-28 13:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foodrequest_img_alter_user_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequest',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 18, 44, 32, 65107)),
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo', to=settings.AUTH_USER_MODEL),
        ),
    ]
