# Generated by Django 4.1 on 2022-11-03 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_foodrequest_date_time_alter_foodrequest_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequest',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 8, 9, 11, 591281)),
        ),
    ]
