# Generated by Django 4.1 on 2022-12-13 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_is_ondrive_alter_foodrequest_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequest',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 9, 57, 432825)),
        ),
    ]
