# Generated by Django 4.1 on 2022-12-13 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_foodrequest_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.city'),
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 22, 0, 45, 499664)),
        ),
    ]
